services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - CHROMA_URL=http://chromadb:8000
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - MODEL_PROVIDER=anthropic
      - MODEL_NAME=claude-3-sonnet-20240229
    volumes:
      - app_data:/tmp/app # Mount the volume
    depends_on:
      - chromadb

  chromadb:
    image: chromadb/chroma:latest
    volumes:
      - chroma_data:/chroma/chroma
    ports:
      - "8000:8000"

volumes:
  chroma_data:
    driver: local
  app_data: # Declare the new volume
    driver: local
