services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - CHROMA_URL=http://chromadb:8000
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - MODEL_PROVIDER=anthropic
      - MODEL_NAME=claude-3-sonnet-20240229
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/chatdb
    volumes:
      - app_data:/tmp/app
    depends_on:
      - chromadb
      - db
    networks:
      - app-network

  chromadb:
    image: chromadb/chroma:latest
    volumes:
      - chroma_data:/chroma/chroma
    ports:
      - "8000:8000"
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chatdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - app-network

volumes:
  chroma_data:
    driver: local
  app_data:
    driver: local
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
